#!/bin/sh

if [ -z $1 ]; then
    echo "Usage:\n\ne [filename]"
    exit 1
fi

VIMPATH=`which vim`
for f in $1 $2 $3 $4 $5; do
    $VIMPATH --not-a-term --clean --noplugin -n -R -c "set runtimepath^=$HOME/.vim/plugged/vim-floaterm" -c "call floaterm#edita#vim#client#open()" $f
done;
