#!/usr/bin/env bash

set -eu

# This script flashes and debugs an stm32 application.  Make sure to start an STM32 project in
# CubeIDE and build the project once in the IDE before using this application.
# Install the STM32 Programmer here https://www.st.com/en/development-tools/stm32cubeprog.html
# Install the CubeIDE here https://www.st.com/en/development-tools/stm32cubeide.html


# GDB Server is installed with the CubeIDE, find the path to ST-LINK_gdbserver.
GDB_SERVER_PATH="/home/nwitt/.local/share/flatpak/app/com.st.STM32CubeIDE/x86_64/stable/db34c86b832bce799c2412abf74a417ef6da31cffcc9850dc97a3694f2cba196/files/stm32cubeide/plugins/com.st.stm32cube.ide.mcu.externaltools.stlink-gdb-server.linux64_2.0.200.202202231230/tools/bin/ST-LINK_gdbserver"
# GDB is installed with the CubeIDE, find the path to arm-none-eabi-gdb.
GDB_PATH="/home/nwitt/.local/share/flatpak/app/com.st.STM32CubeIDE/x86_64/stable/db34c86b832bce799c2412abf74a417ef6da31cffcc9850dc97a3694f2cba196/files/stm32cubeide/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/arm-none-eabi-gdb"
GCC_TOOLS_PATH="/home/nwitt/.local/share/flatpak/app/com.st.STM32CubeIDE/x86_64/stable/db34c86b832bce799c2412abf74a417ef6da31cffcc9850dc97a3694f2cba196/files/stm32cubeide/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin"
# STM32 Programmer install path
STM32_PROGRAMMER_PATH="/home/nwitt/workspace/STM32Cube/STM32CubeProgrammer"
# STM32 Programmer CLI path
STM32_PROGRAMMER_CLI_PATH="${STM32_PROGRAMMER_PATH}/bin/STM32_Programmer_CLI"
PATH=${PATH}:${GCC_TOOLS_PATH}

# Build the STM32 Application
make -C ./Debug all

# Flash the application onto the STM32
eval "${STM32_PROGRAMMER_CLI_PATH} -c port=SWD -w ./Debug/*.elf"

# Create a new tmux session for the gdb server
tmux kill-session -t "gdb-server" || true
unset TMUX
tmux new-session -d -s "gdb-server" -c ${STM32_PROGRAMMER_PATH}
tmux send-keys -t gdb-server "${GDB_SERVER_PATH} --swd --initialize-reset" Enter

# Attach a gdb session to the server
${GDB_PATH} --se=$(echo ./Debug/*.elf) -ex 'target remote localhost:61234' -ex 'tui enable'
